#!/usr/bin/env bash

# track the storms from the extrema
BASE_PATH=$HOME/wah_data/Batch48/1985/hadam3p_eu_ins0_1985_1_008476005_0/ga.pd
IN_DIR=$BASE_PATH/field8
OUT_DIR=$BASE_PATH/field8/track_out/L$1
EXE_PATH=$HOME/Coding/tri_tracker/exe

#$1             # regrid level
#$2             # extrema detection level
#$3             # large scale feature level
#$4             # number of optimisation steps

LEV=$1              # regrid level
EX_LEV=$2           # extrema detection level
LS_LEV=$3           # large scale feature level
PMODE=0
OPT_STEPS=$4        # number of optimisation steps
GRID_FILE=./grids/precis_mesh_EU"_L"$LEV
STASH=16222.inst
GP_STASH=16202
TRK_ARGS="-r 1000 -f 6 -v 10 -s $OPT_STEPS -T"

#for yr in {1989..2008};
RGD_FNAME=ins0ga.pdi5dec_pdi6mar_field8_L$LEV"".rgd
RGD_FILE=$OUT_DIR"/"$RGD_FNAME
EX_FILE=${RGD_FILE/"_L"$LEV".rgd"/"_L"$LEV"_E"$EX_LEV"_S"$LS_LEV".ex"}
TRK_FILE=${EX_FILE/".ex"/".trk"}
cmd="$EXE_PATH/track -i $EX_FILE -o $TRK_FILE $TRK_ARGS"
echo $cmd
$cmd

