#!/usr/bin/env bash

# generate the  grid for the PRECIS regional model run from 1989->2008
MSLP_DIR=$HOME/precis_output/oxfag/16222.inst/cat_six_hour_seas
MSLP_FNAME=oxfaga.dec1989.apr1990.16222.inst_6hr.nc
IN_FILE=$MSLP_DIR/"/"$MSLP_FNAME

EXE_PATH=$HOME/Coding/tri_tracker/exe

LEV=$1
GRID_FILE=./grids/precis_mesh_EU_L""$LEV
NC_VAR=p
ITS=0

cmd="$EXE_PATH/gen_grid -f $IN_FILE -v $NC_VAR -o $GRID_FILE -I $ITS -l $LEV"
echo $cmd
$cmd
